import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { mapTikTokItem, isTikTokItemRaw, type TikTokItemRaw } from "../platforms/tiktok-item";
import { extractHashtags } from "../observe";

const capture = JSON.parse(readFileSync(new URL("./fixtures/tiktok-capture.json", import.meta.url), "utf8")) as {
  itemWithCaptions: TikTokItemRaw;
  itemWithoutCaptions: TikTokItemRaw;
};

test("real For-You item with auto captions maps to a complete FeedItem", () => {
  const raw = capture.itemWithCaptions;
  assert.ok(isTikTokItemRaw(raw));
  assert.equal(typeof raw.author, "object", "fixture is the API shape (author object)");
  const author = raw.author as { uniqueId: string };
  const mapped = mapTikTokItem(raw, 1_000);
  assert.ok(mapped);
  const { item, extras } = mapped;

  assert.equal(item.id, `tiktok:${raw.id}`);
  assert.equal(item.platform, "tiktok");
  assert.equal(item.author.handle, author.uniqueId);
  assert.equal(item.url, `https://www.tiktok.com/@${author.uniqueId}/video/${raw.id}`);
  assert.ok(item.text.length > 0);
  assert.equal(item.scrapedAt, 1_000);
  assert.equal(item.createdAt, new Date(raw.createTime! * 1000).toISOString());
  assert.equal(item.media.length, 1);
  assert.equal(item.media[0]!.type, "video");
  assert.match(item.media[0]!.url, /^https:\/\//);

  // every hashtag we report occurs in the text (structured source and regex source must agree on membership)
  for (const tag of item.hashtags) assert.ok(item.text.toLowerCase().includes(`#${tag}`), `hashtag #${tag} not in text`);
  assert.deepEqual([...item.hashtags].sort(), [...new Set(extractHashtags(item.text))].sort());

  assert.ok(extras.caption, "caption track expected");
  assert.match(extras.caption!.url, /^https:\/\//);
  assert.ok(extras.caption!.urls.length >= 2, "CDN variants kept for fallback");
  assert.equal(extras.caption!.urls[0], extras.caption!.url);
  assert.equal(new Set(extras.caption!.urls).size, extras.caption!.urls.length, "variants deduplicated");
  assert.equal(extras.caption!.autoGenerated, true);
  assert.equal(extras.language, "en");
  assert.equal(extras.durationSec, raw.video!.duration);
  assert.equal(extras.stats?.likes, raw.stats!.diggCount);
  assert.equal(extras.isAd, false);
});

test("React-state shape (author as string, nickname on the item) without a caption track", () => {
  const raw = capture.itemWithoutCaptions;
  assert.equal(typeof raw.author, "string", "fixture is the React-state shape");
  assert.ok(isTikTokItemRaw(raw));
  const mapped = mapTikTokItem(raw);
  assert.ok(mapped);
  assert.equal(mapped.extras.caption, undefined);
  assert.equal(mapped.item.author.handle, raw.author);
  assert.equal(mapped.item.author.displayName, raw.nickname);
  assert.equal(mapped.item.author.verified, undefined);
  assert.equal(mapped.item.media[0]?.type, "video");
  assert.deepEqual(mapped.extras.stickerTexts, ["Germany 🇩🇪"]);
  assert.equal(mapped.extras.stats?.likes, raw.stats!.diggCount);
});

test("structured hashtags and mentions win over regex parsing", () => {
  const mapped = mapTikTokItem({
    id: "1",
    desc: "hello #World @someone",
    author: { uniqueId: "a" },
    textExtra: [
      { type: 1, hashtagName: "world" },
      { type: 0, userUniqueId: "someone" },
    ],
    video: { playAddr: "https://v.example/1.mp4", duration: 3 },
  });
  assert.ok(mapped);
  assert.deepEqual(mapped.item.hashtags, ["world"]);
  assert.deepEqual(mapped.extras.mentions, ["someone"]);
});

test("photo carousels map to image media and the description prefers contents[].desc", () => {
  const mapped = mapTikTokItem({
    id: "2",
    desc: "short",
    contents: [{ desc: "short but the full version #tag" }],
    author: { uniqueId: "b", nickname: "B", verified: true },
    imagePost: { title: "Slides", images: [{ imageURL: { urlList: ["https://i.example/1.jpg"] } }, { imageURL: { urlList: ["https://i.example/2.jpg"] } }] },
    video: { playAddr: "https://v.example/ignored.mp4" },
  });
  assert.ok(mapped);
  assert.equal(mapped.item.text, "short but the full version #tag");
  assert.deepEqual(mapped.item.hashtags, ["tag"]);
  assert.equal(mapped.item.media.length, 2);
  assert.equal(mapped.item.media[0]!.type, "image");
  assert.equal(mapped.item.author.verified, true);
});

test("garbage input is rejected instead of throwing", () => {
  assert.equal(isTikTokItemRaw(null), false);
  assert.equal(isTikTokItemRaw({ id: 123 }), false);
  assert.equal(isTikTokItemRaw({ id: "", author: "a" }), false, "empty id");
  assert.equal(isTikTokItemRaw({ id: "1", author: "" }), false, "empty string author");
  assert.equal(isTikTokItemRaw({ id: "1", author: "a" }), true, "React-state shape");
  assert.equal(isTikTokItemRaw({ id: "1", author: {} }), true, "API shape");
  assert.equal(mapTikTokItem({} as TikTokItemRaw), null);
});
