/**
 * TikTok item JSON → FeedItem. The raw shape is what `/api/recommend/item_list/` (and the React state
 * behind each feed article) delivers; only the fields we read are typed, everything is optional because
 * TikTok changes this payload without notice. Verified against real captures on 2026-09-21
 * (see scraper/test/fixtures/tiktok-capture.json and scraper/RESEARCH.md).
 */
import type { FeedItem, MediaRef } from "@contracts";
import { extractHashtags, uniq } from "../observe";

interface TextExtra {
  type?: number;
  hashtagName?: string;
  userUniqueId?: string;
}

export interface TikTokCaptionInfo {
  url?: string;
  urlList?: string[];
  language?: string;
  languageCode?: string;
  isAutoGen?: boolean;
  isOriginalCaption?: boolean;
  captionFormat?: string;
}

export interface TikTokItemRaw {
  id?: string;
  desc?: string;
  createTime?: number;
  textLanguage?: string;
  isAd?: boolean;
  AIGCDescription?: string;
  /**
   * Two shapes seen in the wild (both in scraper/test/fixtures/tiktok-capture.json): the API payload carries an
   * author OBJECT; the item held in React state carries the handle as a STRING plus `nickname`/`authorId` on the item.
   */
  author?: string | { uniqueId?: string; nickname?: string; verified?: boolean };
  nickname?: string;
  authorId?: string;
  stats?: { diggCount?: number; commentCount?: number; shareCount?: number; playCount?: number; collectCount?: number };
  music?: { title?: string; authorName?: string; original?: boolean };
  textExtra?: TextExtra[];
  contents?: { desc?: string; textExtra?: TextExtra[] }[];
  challenges?: { title?: string }[];
  video?: {
    playAddr?: string;
    cover?: string;
    originCover?: string;
    duration?: number;
    claInfo?: {
      captionInfos?: TikTokCaptionInfo[];
      originalLanguageInfo?: { languageCode?: string };
      noCaptionReason?: number;
      hasOriginalAudio?: boolean;
    };
    subtitleInfos?: { Url?: string; LanguageCodeName?: string; Source?: string; Format?: string }[];
  };
  stickersOnItem?: { stickerText?: string[] }[];
  imagePost?: { title?: string; images?: { imageURL?: { urlList?: string[] } }[] };
}

/** Data TikTok provides that has no FeedItem field (yet). Documented as contract proposals in RESEARCH.md. */
export interface TikTokExtras {
  /** WebVTT subtitle track chosen for the transcript channel (original language preferred). `urls` = all CDN variants, try in order. */
  caption?: { url: string; urls: string[]; language?: string; autoGenerated: boolean };
  language?: string;
  durationSec?: number;
  stats?: { likes?: number; comments?: number; shares?: number; views?: number; saves?: number };
  music?: { title?: string; author?: string; original?: boolean };
  /** On-screen text stickers — often the actual message of a video without speech. */
  stickerTexts: string[];
  mentions: string[];
  isAd: boolean;
  aigcLabel?: string;
}

export interface MappedTikTok {
  item: FeedItem;
  extras: TikTokExtras;
  /** TikTok's own numeric id (FeedItem.id is `tiktok:<rawId>`). */
  rawId: string;
}

export function isTikTokItemRaw(v: unknown): v is TikTokItemRaw {
  if (!v || typeof v !== "object") return false;
  const r = v as TikTokItemRaw;
  if (typeof r.id !== "string" || r.id.length === 0) return false;
  return (typeof r.author === "string" && r.author.length > 0) || (!!r.author && typeof r.author === "object");
}

function authorOf(raw: TikTokItemRaw): FeedItem["author"] {
  if (typeof raw.author === "string") return { handle: raw.author.trim(), displayName: raw.nickname || undefined };
  return { handle: raw.author?.uniqueId?.trim() ?? "", displayName: raw.author?.nickname || raw.nickname || undefined, verified: raw.author?.verified };
}

export function mapTikTokItem(raw: TikTokItemRaw, now: number = Date.now()): MappedTikTok | null {
  const rawId = raw.id;
  if (!rawId) return null;
  const author = authorOf(raw);
  const handle = author.handle;
  const text = fullDescription(raw);
  const structured = [...(raw.textExtra ?? []), ...(raw.contents ?? []).flatMap((c) => c.textExtra ?? [])];

  const item: FeedItem = {
    id: `tiktok:${rawId}`,
    platform: "tiktok",
    url: handle ? `https://www.tiktok.com/@${handle}/video/${rawId}` : undefined,
    author,
    text,
    hashtags: pickHashtags(structured, raw.challenges, text),
    media: mediaOf(raw),
    createdAt: raw.createTime ? new Date(raw.createTime * 1000).toISOString() : undefined,
    scrapedAt: now,
  };

  const caption = pickCaption(raw);
  const extras: TikTokExtras = {
    caption,
    language: raw.textLanguage || raw.video?.claInfo?.originalLanguageInfo?.languageCode || undefined,
    durationSec: raw.video?.duration,
    stats: raw.stats
      ? { likes: raw.stats.diggCount, comments: raw.stats.commentCount, shares: raw.stats.shareCount, views: raw.stats.playCount, saves: raw.stats.collectCount }
      : undefined,
    music: raw.music ? { title: raw.music.title, author: raw.music.authorName, original: raw.music.original } : undefined,
    stickerTexts: (raw.stickersOnItem ?? []).flatMap((s) => s.stickerText ?? []).map((t) => t.trim()).filter(Boolean),
    mentions: uniq(structured.map((t) => t.userUniqueId ?? "").filter(Boolean)),
    isAd: !!raw.isAd,
    aigcLabel: raw.AIGCDescription || undefined,
  };
  return { item, extras, rawId };
}

/** `contents[].desc` carries the full description; `desc` is the same text (or a shortened form on some items). */
function fullDescription(raw: TikTokItemRaw): string {
  const joined = (raw.contents ?? []).map((c) => c.desc ?? "").filter(Boolean).join("\n").trim();
  const plain = (raw.desc ?? "").trim();
  return joined.length >= plain.length ? joined : plain;
}

/** Primary: structured `textExtra` (exact, no parsing). Fallback 1: `challenges`. Fallback 2: regex over the text. */
function pickHashtags(structured: TextExtra[], challenges: { title?: string }[] | undefined, text: string): string[] {
  const fromExtra = uniq(structured.map((t) => (t.hashtagName ?? "").toLowerCase()).filter(Boolean));
  if (fromExtra.length) return fromExtra;
  const fromChallenges = uniq((challenges ?? []).map((c) => (c.title ?? "").toLowerCase()).filter(Boolean));
  if (fromChallenges.length) return fromChallenges;
  return extractHashtags(text);
}

function mediaOf(raw: TikTokItemRaw): MediaRef[] {
  const media: MediaRef[] = [];
  const images = raw.imagePost?.images ?? [];
  for (const img of images) {
    const url = img.imageURL?.urlList?.[0];
    if (url) media.push({ type: "image", url, altText: raw.imagePost?.title || undefined });
  }
  if (!images.length && raw.video?.playAddr) {
    media.push({ type: "video", url: raw.video.playAddr, posterUrl: raw.video.cover || raw.video.originCover || undefined });
  }
  return media;
}

/**
 * Subtitle track selection. `claInfo.captionInfos` is the current field (2026), `subtitleInfos` the legacy one;
 * both were present on the same items in our captures. Prefer the original-language track.
 */
function pickCaption(raw: TikTokItemRaw): TikTokExtras["caption"] {
  const infos = raw.video?.claInfo?.captionInfos ?? [];
  const chosen = infos.find((c) => c.isOriginalCaption) ?? infos[0];
  const urls = uniq([chosen?.url ?? "", ...(chosen?.urlList ?? [])].filter(Boolean));
  if (chosen && urls.length) {
    return { url: urls[0]!, urls, language: chosen.languageCode || chosen.language, autoGenerated: !!chosen.isAutoGen };
  }
  const legacy = raw.video?.subtitleInfos ?? [];
  const orig = raw.video?.claInfo?.originalLanguageInfo?.languageCode;
  const legacyPick = legacy.find((s) => orig && s.LanguageCodeName?.toLowerCase().startsWith(orig)) ?? legacy[0];
  if (legacyPick?.Url) {
    return { url: legacyPick.Url, urls: [legacyPick.Url], language: legacyPick.LanguageCodeName, autoGenerated: legacyPick.Source === "ASR" };
  }
  return undefined;
}
